# -*- coding: utf-8 -*-
"""nayawebsite.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BM53fWrhZdo94r0Jwa394tl9vo1ha1ew
"""

!pip install langchain langchain-groq langchain-core -q

!pip install streamlit -q

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# from langchain_groq import ChatGroq
# from langchain_core.messages import HumanMessage, AIMessage
# from langchain_core.messages import SystemMessage
# from typing import Annotated, Literal
# from typing_extensions import TypedDict
# from langgraph.graph.message import add_messages
# from langgraph.graph import StateGraph, START, END
# 
# class State(TypedDict):
#     messages : Annotated[list, add_messages]
#     draft: str
#     feedback: str
#     round_number: int
# 
# def writer_node(state: State):
#     round_num = state.get("round_number", 0) # If no round number (in first try) then default 0
# 
#     if round_num == 0: # No feedback yet
#         user_request = state['messages'][-1].content # Last messsage will be the user request
#         prompt = f"Write a clear 3-4 sentence explanation of {user_request}"
# 
#     else: # More than 0 round, so feedback is there
#         prompt = f"""Improve this draft based on the feedback below.
#                      Write the improved version only. No preamble.
#                      Draft: {state['draft']}
#                      Feedback : {state['feedback']}"""
# 
# 
#     draft = llm.invoke([
#                 SystemMessage(
#                   content="You are an expert essay writer. Write a proper essay within 300 words."
#                 ),
#                 HumanMessage(content=prompt)
#             ]).content
#     print(f"\n✏️  Writer (round {round_num + 1}):\n{draft}")
# 
#     return {"draft": draft, "round_number": round_num + 1}
# 
# # Critic node — reads the draft and decides if it is good enough
# def critic_node(state: State):
#     draft = state["draft"]
# 
#     prompt = f"""You are a strict critic. Read this draft carefully.
# 
# Draft:
# {draft}
# 
# If the draft is clear, accurate, and complete — respond with exactly: APPROVED
# If it needs improvement — respond with: NEEDS WORK: (then your specific feedback on one line)"""
# 
#     feedback = llm.invoke([
#       SystemMessage(
#         content="You are a strict writing critic."
#       ),
#       HumanMessage(content=prompt)
#     ]).content
#     print(f"\n🔍 Critic (round {state['round_number']}):\n{feedback}")
#     return {"feedback": feedback}
# 
# def should_continue(state: State) -> Literal['writer', END]:
#     feedback = state['feedback']
#     round_number = state['round_number']
# 
#     if 'APPROVED' in feedback or round_number >= 3:
#         print("\n✅ Critic approved. Stopping.")
#         return END
# 
#     else:
#         print("\n🔁 Critic not satisfied. Sending back to writer.")
#         return "writer"
# 
# builder = StateGraph(State)
# builder.add_node("writer", writer_node)
# builder.add_node("critic", critic_node)
# builder.add_edge(START, "writer")
# builder.add_edge("writer", "critic")
# builder.add_conditional_edges("critic", should_continue)
# reflection_graph = builder.compile()
# 
# st.title('🌍 The Essay Agent')
# st.write("Ask me topic for essay. I will browse the web and write essay on the topic.")
# 
# # 1. Sidebar Configuration
# with st.sidebar:
#     st.header('⚙️ System Config')
#     user_api_key = st.text_input('Groq API Key:', type='password')
#     st.info('Equipped with: Essay writing Tool')
# 
# 
# # 2. The Memory
# if 'messages' not in st.session_state:
#     st.session_state.messages = []
# 
# # 3. Draw the Chat History
# for msg in st.session_state.messages:
#     with st.chat_message(msg['role']):
#         st.markdown(msg['content'])
# 
# # 4. The CORE Agentic AI Loop:
# if user_query := st.chat_input("Write a topic for essay"):
# 
#     if not user_api_key:
#         st.error('Please enter your API Key in the sidebar')
# 
#     else:
#         # A. Display the user message instantly
#         st.session_state.messages.append({'role': 'user', 'content': user_query})
#         with st.chat_message('user'):
#             st.markdown(user_query)
# 
#         # Initialise the LLM and the Langgraph Agent
#         llm = ChatGroq(temperature=0, model_name='llama-3.3-70b-versatile', api_key = user_api_key)
#         system_prompt_text = """
#                             You are a Essay writing assistant. You MUST write a proper essay within 300 word only. Answer the query clearly.
#                              """
# 
#         system_message = SystemMessage(content=system_prompt_text)
# 
#         langgraph_history = []
# 
#         for msg in st.session_state.messages:
#             if msg['role'] == 'user':
#                 langgraph_history.append(HumanMessage(content=msg['content']))
# 
#             else:
#                 langgraph_history.append(AIMessage(content=msg['content']))
# 
#         # D. Execute the Agent (with a visual loading spinner)
#         with st.chat_message('assistant'):
#             with st.spinner("✍️ Writing and reviewing essay..."):
# 
#                 # We feed the translated history into the graph
#                 result_state = reflection_graph.invoke({'messages': langgraph_history, "draft": "", "feedback": "", "round_number": 0})
# 
#                 # The final answer, which is the last message
#                 bot_answer = result_state["draft"]
# 
#             st.markdown(bot_answer)
# 
#         # E. Save the final answer back into streamlit memory
#         st.session_state.messages.append({"role": "assistant", "content": bot_answer})

!pip install pyngrok -q

from pyngrok import ngrok
import subprocess
import time

ngrok.set_auth_token("3FwzdNkpYwJEGdEeJZTFruxhNS3_65xAFeqeFCCF5cHrhyqtA")

# Start streamlit as a background process (doesn't block)
subprocess.Popen(["streamlit", "run", "app.py"])

# Wait for Streamlit to fully start
time.sleep(5)

# Connect ngrok
public_url = ngrok.connect(8501)
print("✅ Your app is live at:", public_url)